sudo: false

language: node_js

node_js: 6

install:
  - npm install
  - npm run wd:update

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run validate
  - npm run build
  - npm run test:unit
