language: node_js

sudo: false

node_js: 6

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: 8384f582df86e21e51a470faea97703eaf43b3cf719346dc026f38d86d9b000e

install:
  - npm install

after_install:
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run validate
  - npm run build
  - npm run test

after_success:
  - npm run release

branches:
  only:
    - master
