language: node_js
sudo: false
node_js:
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
after_install:
  - npm prune
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run validate
  - npm run build
  - npm run test
